added openai api prereq credits to prevent limit rate error
landing-ai/vision-agent pull request #136
Opened 2024-06-13 22:22 UTC by moutasemalakkad

2024-06-14 00:04 UTC, dillonalaird commented
Awesome, thanks! I would add a small sentence if at the top of the doc, and then add the entire section at the end of the doc with the details. This way people can still get to the main usage section quickly without scrolling too far down.

Also, please copy the text to docs/index.md as well for the documentation page.

2024-06-14 15:08 UTC, dillonalaird requested changes
Awesome, thanks! I would add a small sentence if at the top of the doc, and then add the entire section at the end of the doc with the details. This way people can still get to the main usage section quickly without scrolling too far down.

Also, please copy the text to docs/index.md as well for the documentation page.

2024-06-15 20:32 UTC, moutasemalakkad commented
@dillonalaird Please let me know if that looks good. I have also added a divider at the bottom to keep a bottom section for non landingAI's specific notes (other apis etc..). Let me know if you like the formatting or you'd like something else

2024-06-15 20:34 UTC, moutasemalakkad commented on docs/index.md
> +******************************************************************************************************************************
Happy to change the formatting here

2024-06-21 22:35 UTC, humpydonkey approved these changes
LGTM
thanks for the contribution

2024-06-21 22:35 UTC, merged