fix get_embedding in class AzureSim, passing self.emb_call instead of…
landing-ai/vision-agent pull request #239
Opened 2024-09-19 01:51 UTC by hieutrtr

When using AzureVisionAgentCoder, I got error of `TypeError: 'AzureOpenAI' object is not callable`

![image](https://github.com/user-attachments/assets/0ada7200-b4e1-435c-b582-81b9ff20338c)

Fixed it with just a simple code change.

2024-09-22 02:43 UTC, hieutrtr commented
Dear @AsiaCao @dillonalaird , as I see you guys are top contributors, could you please help to review my PR here.
Or something else I need to comply, please advise.

Thanks !

2024-09-23 17:59 UTC, dillonalaird requested changes
Than you for contributing! The PR looks good, could you just run `black` to fix the formatting issue?

2024-09-27 03:58 UTC, hieutrtr commented
> Than you for contributing! The PR looks good, could you just run `black` to fix the formatting issue?

Hi @dillonalaird , I reformatted it with `black` please help to review. Thanks !

2024-09-27 15:06 UTC, dillonalaird approved these changes
Looks good, thank you for your contribution!

2024-09-27 15:07 UTC, merged