sam2 large video support
landing-ai/vision-agent pull request #335
Opened 2024-12-31 19:44 UTC by hrnn

2025-01-06 23:34 UTC, camiloaz approved these changes
LGTM! I am assuming there were already tests for the object tracking case?

2025-01-06 23:34 UTC, camiloaz commented
> LGTM! I am assuming there were already tests for the object tracking case?

let's wait for @dillonalaird review.

2025-01-06 23:52 UTC, dillonalaird requested changes
Added a few comments on how to handle the display data

2025-01-06 23:52 UTC, dillonalaird commented on vision_agent/tools/tools.py
> +        _LOGGER.debug("Starting processing for segment %d.", segment_index + 1)
I would remove the logging, because the ipython notebook catches this and it ends up in the observation to the agent.

2025-01-06 23:52 UTC, dillonalaird commented on vision_agent/utils/video_tracking.py
> +            return_frame_data.append(
Display data is "labels", "rle" and "bboxes" where "bboxes" are unnormalized coordinates. This is for the front end to display. Return data is "label", "mask" and "bboxes" where "bboxes" are normalized.

Here in return_data you are adding in the "rle" and not adding in "bboxes", but you need to track a separate display_data list to track the items listed above

2025-01-07 05:43 UTC, hrnn commented on vision_agent/tools/tools.py
> +        _LOGGER.debug("Starting processing for segment %d.", segment_index + 1)
Removed

2025-01-07 05:43 UTC, hrnn commented on vision_agent/utils/video_tracking.py
> +            return_frame_data.append(
Good catch, fixed.

2025-01-07 20:55 UTC, hrnn commented on vision_agent/utils/video_tracking.py
> +            return_frame_data.append(
Hi @dillonalaird 
these are captures from the results
| return_data  | display_data  |
| --- | --- |
| ![Screenshot 2025-01-07 165030](https://github.com/user-attachments/assets/cd8eaf74-b983-40ef-a332-7d26e845a8cb)| ![Screenshot 2025-01-07 164958](https://github.com/user-attachments/assets/2f05140f-3776-4196-9cd6-042d3409d4f7)|

2025-01-07 23:34 UTC, dillonalaird approved these changes
LGTM

2025-01-07 23:35 UTC, merged